#!/bin/bash

BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"
BRANCH_REGEX="^(epic\/[0-9]+\/[0-9a-z\-]+|topic\/[0-9]+\/[0-9a-z\-]+|main)$"
if [[ ! $BRANCH_NAME =~ $BRANCH_REGEX ]]
then
  echo "ERROR - Push failed"
  echo "Branch name does not match schema."
  echo " - main"
  echo " - epic/<milestone>/new-version"
  echo " - topic/<issue>/some-bug-or-feature"
  exit 1
fi