#!/bin/bash

# check that npm installed
if ! command -v npm &> /dev/null
then
    echo "ERROR - Commit failed"
    echo "npm could not be found."
    exit 1
fi

# create temp file for post-commit
touch .commit
